services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app/data/friands.db:/app/data/friands.db
      - ./app:/app:rw

    env_file:
      - .env
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_PORT: "8501"
      STREAMLIT_SERVER_ENABLECORS: "false"
      LANG: "fr_FR.UTF-8"
      LANGUAGE: "fr_FR:fr"
      LC_ALL: "fr_FR.UTF-8"
