[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "friands"
version = "0.1.0"
description = "Finding Restaurants, Insights And Notably Delectable Spots"

[tool.setuptools]
packages = ["src"]
package-dir = {"" = "."}